aa: None
adv_training: pgd
attack: fgsm
attack_boundaries:
- 0
- 1
attack_eps: 8
attack_lr: 2
attack_norm: linf
attack_steps: 7
amp: false
aug_splits: 0
batch_size: 128
bce_loss: false
bce_target_thresh: null
bn_eps: null
bn_momentum: null
bn_tf: false
channels_last: false
checkpoint_hist: 10
clip_grad: null
clip_mode: norm
color_jitter: 0.25
cooldown_epochs: 10
crop_pct: null
cutmix: 0.0
cutmix_minmax: null
data_dir: /p/vast1/MLdata
dataset: torch/cifar10
decay_epochs: null
decay_milestones:
- 50
- 100
decay_rate: 0.1
dist_bn: reduce
drop: 0.0
drop_block: null
drop_connect: null
drop_path: null
epoch_repeats: 0.0
epochs: 150
eps_schedule: constant
eps_schedule_period: 10
eval_metric: robust_top1
experiment: pgd-adv-training-repro
force_cpu: false
gp: null
hflip: 0.5
img_size: null
initial_checkpoint: ''
input_size:
- 3
- 32
- 32
interpolation: ''
jsd_loss: false
local_rank: 0
log_interval: 50
log_wandb: false
lr: null
lr_base: 0.1
lr_base_size: 128
lr_cycle_decay: 0.5
lr_cycle_limit: 1
lr_cycle_mul: 1.0
lr_k_decay: 1.0
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
mean:
- 0.4914
- 0.4822
- 0.4465
min_lr: 1.0e-05
mixup: 0.0
mixup_mode: batch
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_switch_prob: 0.5
model: wide_resnet_28_10
model_ema: false
model_ema_decay: 0.999
momentum: 0.9
no_aug: false
no_normalize: false
no_resume_opt: false
normalize_model: true
num_classes: 10
opt: sgd
opt_betas: null
opt_eps: 1.0e-8
output: /p/gpfs1/robustHW
pad: 4
patience_epochs: 10
pin_mem: false
pretrained: false
rand_rotation: 2
ratio:
- 1.0
- 1.0
recount: 1
recovery_interval: 0
remode: pixel
reprob: 0.0
resplit: false
resume: ''
save_images: false
scale:
- 1.0
- 1.0
sched: multistep
seed: 42
smoothing: 0.0
split_bn: false
start_epoch: null
std:
- 0.2023
- 0.1994
- 0.2010
sync_bn: false
torchscript: false
train_interpolation: bicubic
train_split: train
tta: 0
use_multi_epochs_loader: false
val_split: validation
validation_batch_size: null
vflip: 0.0
warmup_epochs: 0
warmup_lr: 1.0e-6
weight_decay: 5e-4
workers: 4
